# Generated by Django 6.0 on 2025-12-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtapp', '0002_customer_user_debt_user_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='status',
            field=models.CharField(choices=[('owing', 'Owing'), ('paid', 'Paid'), ('part', 'Part')], default='owing', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('owing', 'Owing'), ('paid', 'Paid'), ('part', 'Part')], default='owing', max_length=100),
        ),
    ]
