# Generated by Django 6.0 on 2025-12-27 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtapp', '0004_expenditure_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='debtapp.payment'),
        ),
    ]
