# Generated by Django 6.0 on 2025-12-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtapp', '0005_debt_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='balance',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_collected',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
