# Generated by Django 6.0 on 2025-12-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtapp', '0006_remove_payment_balance_payment_amount_collected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('owing', 'Owing'), ('paid', 'Paid'), ('part', 'Part')], default='part', max_length=100),
        ),
    ]
